apiVersion: v1
kind: ConfigMap
metadata:
  name: yaruki-printer-config
data:
  preview.json: |
    {
      "cpl": 36,
      "encoding": "shiftjis",
      "spacing": false,
      "landscape": false,
      "command": "svg"
    }
  print.json: |
    {
      "cpl": 36,
      "encoding": "shiftjis",
      "spacing": false,
      "landscape": false,
      "upsideDown": true,
      "command": "sii",
      "host": "10.0.0.100",
      "port": 9100
    }
