apiVersion: v1
kind: ConfigMap
metadata:
  name: yaruki-ui-config
data:
  config.json: |-
    {
      "projects": [
        "生活",
        "仕事",
        "趣味",
        "その他"
      ],
      "priorities": [
        "なるはや",
        "最優先",
        "じっくり検討"
      ],
      "durations": [
        "30分",
        "1時間",
        "2時間",
        "半日",
        "1日",
        "3日"
      ],
      "deadlines": [
        {
          "display": "**本日中**",
          "print": "`本日中`"
        },
        {
          "display": "**明日中**",
          "print": "`明日中`"
        },
        {
          "display": "**今週中**",
          "print": "`今週中`"
        },
        {
          "display": "朝イチ",
          "print": "`%m/%d 朝`"
        },
        {
          "display": "お昼",
          "print": "`%m/%d 昼`"
        },
        {
          "display": "定時",
          "print": "`%m/%d 定時`"
        }
      ],
      "style": {
        "css_paths": [
          "/config/yaruki-ui/default.css"
        ],
        "projects_per_row": 4,
        "priorities_per_row": 3,
        "durations_per_row": 6,
        "deadlines_per_row": 3
      },
      "print": {
        "template_path": "/config/yaruki-ui/default.receipt.tmpl",
        "output_dir": "/output"
      }
    }
  default.receipt.tmpl: |- # this file is newline-sensitive
    {% if priority == "" and project != "" %}|^^{{ project }}
    {% endif -%}
    {% if priority != "" and project == "" %}|^^`{{ priority }}`
    {% endif -%}
    {% if priority != "" and project != "" %}|^^`{{ priority }}` {{ project }}
    {% endif -%}
    |^^`{{ title }}`
    {width:9 *}
    {{ receipt_date_index_format }}受付時刻 |{{ receipt_date_format }}{{ receipt_date }}
    {{ deadline_index_format }}締切時刻 |{{ deadline_format }}{{ deadline }}
    {{ duration_index_format}}所要時間 |{{ duration_format }}{{ duration -}}
    {% if body != "" %}
    {{ body_index_format }}メモ |{{ body_format }}{{ body }}{% endif -%}
  default.css: |-
    /* paste your css here */
